debug: True                     # TODO: Remove for proper benchmarking

phenotypes:
    Triglycerides_standardized:
        correction_method: FDR
        n_training_genes: 40

baseline_results:
    -
        base: /omics/odcf/analysis/OE0540_projects/ukbb/experiments/baseline_brian/all_phenos_beta_weighted_burden_maf_0.001_eaf50
        type: plof/burden
    -
        base: /omics/odcf/analysis/OE0540_projects/ukbb/experiments/baseline_brian/all_phenos_beta_weighted_burden_maf_0.001_eaf50
        type: missense/burden
    -
        base: /omics/odcf/analysis/OE0540_projects/ukbb/experiments/baseline_brian/all_phenos_beta_weighted_burden_maf_0.001_eaf50
        type: plof/skat
    -
        base: /omics/odcf/analysis/OE0540_projects/ukbb/experiments/baseline_brian/all_phenos_beta_weighted_burden_maf_0.001_eaf50
        type: missense/skat

alpha: 0.05

n_chunks: 40

n_repeats: 8

training:
    min_variant_count: 1
    n_bags: 10                  # NOTE: changed
    drop_n_bags: 2              # NOTE: changed
    train_proportion: 0.8
    dataloader_config:
        num_workers: 0

pl_trainer:
    gpus: 1
    precision: 16
    min_epochs: 1000            # NOTE: changed
    max_epochs: 10000            # NOTE: changed
    log_every_n_steps: 10
    check_val_every_n_epoch: 10

early_stopping:
    mode: min
    patience: 3
    min_delta: 0.00001
    verbose: True

hyperparameter_optimization:
    direction: maximize
    n_trials: 1
    sampler:
        type: TPESampler
        config: {}

model:
    type: DeepSet
    model_collection: agg_models
    checkpoint: combined_agg.pt
    config:
        # input_dim: 36
        phi_layers: 2
            # hparam:
            #     type: int
            #     args:
            #         - 2
            #         - 4
        phi_hidden_dim: 20
            # hparam:
            #     type: int
            #     args:
            #         - 16
            #         - 64
            #     kwargs:
            #         step: 16
        rho_layers: 3
            # hparam:
            #     type: int
            #     args:
            #         - 2
            #         - 4
        rho_hidden_dim: 10
            # hparam:
            #     type: int
            #     args:
            #         - 8
            #         - 32
            #     kwargs:
            #         step: 8
        activation: LeakyReLU #was ReLU
            # hparam:
            #     type: categorical
            #     args:
            #         -
            #             - LeakyReLU
            #             - Tanh
        pool: max
            # hparam:
            #     type: categorical
            #     args:
            #         -
            #             - sum
            #             - max
        # dropout:
        #     hparam:
        #         type: float
        #         args:
        #             - 0.
        #             - 0.6
        #         kwargs:
        #             step: 0.1
        metrics:
            # objective: PearsonCorrTorch
            objective: MSE
            objective_mode: min
            loss: MSE
            all:
                MSE: {}
                PearsonCorrTorch: {}
                MAE: {}
                RSquared: {}
        optimizer:
            type: AdamW
            config: {}

# TODO: Try standardizing annotations
training_data:
    gt_file: genotypes.h5
    dataset_config:
        min_common_af:
            combined_UKB_NFE_AF: 0.01
        phenotype_prefix: genotypes
        x_phenotypes:
            - age
            - genetic_PC_1
            - genetic_PC_2
            - genetic_PC_3
            - genetic_PC_4
            - genetic_PC_5
            - genetic_PC_6
            - genetic_PC_7
            - genetic_PC_8
            - genetic_PC_9
            - genetic_PC_10
            - genetic_PC_11
            - genetic_PC_12
            - genetic_PC_13
            - genetic_PC_14
            - genetic_PC_15
            - genetic_PC_16
            - genetic_PC_17
            - genetic_PC_18
            - genetic_PC_19
            - genetic_PC_20
        annotation_file: current_annotations.parquet
        annotations:
            - combined_UKB_NFE_AF
            - combined_UKB_NFE_AF_MB
            - CADD_PHRED
            - CADD_raw
            - sift_score
            - polyphen_score
            - Consequence_splice_acceptor_variant
            - Consequence_splice_donor_variant
            - Consequence_stop_gained
            - Consequence_frameshift_variant
            - Consequence_stop_lost
            - Consequence_start_lost
            - Consequence_inframe_insertion
            - Consequence_inframe_deletion
            - Consequence_missense_variant
            - Consequence_protein_altering_variant
            - Consequence_splice_region_variant
            - condel_score
            - DeepSEA_PC_1
            - DeepSEA_PC_2
            - DeepSEA_PC_3
            - DeepSEA_PC_4
            - DeepSEA_PC_5
            - DeepSEA_PC_6
            - PrimateAI_score
            - AbSplice_DNA
        use_common_variants: False
        use_rare_variants: True
        rare_embedding:
            type: PaddedAnnotations
            config:
                annotations:
                    - combined_UKB_NFE_AF_MB
                    - CADD_raw
                    - sift_score
                    - polyphen_score
                    - Consequence_splice_acceptor_variant
                    - Consequence_splice_donor_variant
                    - Consequence_stop_gained
                    - Consequence_frameshift_variant
                    - Consequence_stop_lost
                    - Consequence_start_lost
                    - Consequence_inframe_insertion
                    - Consequence_inframe_deletion
                    - Consequence_missense_variant
                    - Consequence_protein_altering_variant
                    - Consequence_splice_region_variant
                    - condel_score
                    - DeepSEA_PC_1
                    - DeepSEA_PC_2
                    - DeepSEA_PC_3
                    - DeepSEA_PC_4
                    - DeepSEA_PC_5
                    - DeepSEA_PC_6
                    - PrimateAI_score
                    - AbSplice_DNA
                thresholds:
                    combined_UKB_NFE_AF: "combined_UKB_NFE_AF < 1e-2"
                    CADD_PHRED:  "CADD_PHRED > 5"
                verbose: True
                low_memory: True
        verbose: True
    dataloader_config:
        batch_size: 64
        num_workers: 8

# TODO: Try standardizing annotations
data:
    gt_file: genotypes.h5
    dataset_config:
        min_common_af:
            combined_UKB_NFE_AF: 0.01
        phenotype_prefix: genotypes
        x_phenotypes:
            # - genetic_sex
            - age
            - genetic_PC_1
            - genetic_PC_2
            - genetic_PC_3
            - genetic_PC_4
            - genetic_PC_5
            - genetic_PC_6
            - genetic_PC_7
            - genetic_PC_8
            - genetic_PC_9
            - genetic_PC_10
            - genetic_PC_11
            - genetic_PC_12
            - genetic_PC_13
            - genetic_PC_14
            - genetic_PC_15
            - genetic_PC_16
            - genetic_PC_17
            - genetic_PC_18
            - genetic_PC_19
            - genetic_PC_20
        annotation_file: current_annotations.parquet
        annotations:
            - combined_UKB_NFE_AF
            - combined_UKB_NFE_AF_MB
            - CADD_PHRED
            - CADD_raw
            - sift_score
            - polyphen_score
            - Consequence_splice_acceptor_variant
            - Consequence_splice_donor_variant
            - Consequence_stop_gained
            - Consequence_frameshift_variant
            - Consequence_stop_lost
            - Consequence_start_lost
            - Consequence_inframe_insertion
            - Consequence_inframe_deletion
            - Consequence_missense_variant
            - Consequence_protein_altering_variant
            - Consequence_splice_region_variant
            - condel_score
            - DeepSEA_PC_1
            - DeepSEA_PC_2
            - DeepSEA_PC_3
            - DeepSEA_PC_4
            - DeepSEA_PC_5
            - DeepSEA_PC_6
            - PrimateAI_score
            - AbSplice_DNA
        gene_file: protein_coding_genes.parquet
        use_common_variants: False
        use_rare_variants: True
        rare_embedding:
            type: PaddedAnnotations
            config:
                annotations:
                    - combined_UKB_NFE_AF_MB
                    - CADD_raw
                    - sift_score
                    - polyphen_score
                    - Consequence_splice_acceptor_variant
                    - Consequence_splice_donor_variant
                    - Consequence_stop_gained
                    - Consequence_frameshift_variant
                    - Consequence_stop_lost
                    - Consequence_start_lost
                    - Consequence_inframe_insertion
                    - Consequence_inframe_deletion
                    - Consequence_missense_variant
                    - Consequence_protein_altering_variant
                    - Consequence_splice_region_variant
                    - condel_score
                    - DeepSEA_PC_1
                    - DeepSEA_PC_2
                    - DeepSEA_PC_3
                    - DeepSEA_PC_4
                    - DeepSEA_PC_5
                    - DeepSEA_PC_6
                    - PrimateAI_score
                    - AbSplice_DNA
                thresholds:
                    combined_UKB_NFE_AF: "combined_UKB_NFE_AF < 1e-3"
                    CADD_PHRED:  "CADD_PHRED > 5"
                gene_file: protein_coding_genes.parquet
                verbose: True
                low_memory: True
        verbose: True
    dataloader_config:
        batch_size: 8
        num_workers: 10

